[package]
name = "beefy-light-client"
version = "0.1.0"
authors = ["Julian Sun <julian@oct.network>"]
edition = "2018"

[dependencies]
borsh = "0.8.1"
beefy-merkle-tree = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", features = ["keccak"], default-features = false }
blake2-rfc = { version = "0.2.18", default-features = false }
byteorder = { version = "1", default-features = false }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
libsecp256k1 = { version = "0.7.0", features = ["static-context"], default-features = false }
mmr-lib = { package = "ckb-merkle-mountain-range", default-features = false, version = "0.3.1" }

[dev-dependencies]
hex-literal = "0.3.1"

[features]
default = ["std"]
std = [
	"beefy-merkle-tree/std",
	"blake2-rfc/std",
	"byteorder/std",
	"codec/std",
	"hex/std",
	"libsecp256k1/std",
	"mmr-lib/std",
]
